import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <body className={(sans.className, 'flex flex-col h-screen max-w-7xl mx-auto')}>
      <Header />
      <div className='flex-auto'>{children}</div>
      <Footer />
    </body>
  );
}
