import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      {/* <body className={inter.className}>{children}</body> */}
      <body className={styles.body}>
        <header className={styles.header}>
          <h1>Demo Note App</h1>
          <nav className={styles.nav}>
            <a href='/'>Home</a>
            <a href='contact'>Contact</a>
            <a href='about'>About</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
